version: "3.3"
services:
  image_enhancement:
    image: image_enhancement
    build: .
    command: ["python3","/app/main.py", "staging"]
    ports:
      - 31558:8080
    volumes:
      - ./logs:/app/logs
    restart: always
